Repository MaMpf-HD/mampf, pull requests merged in 2023-04, with the labels that each got.

#444 Redesign landing page
  .gitattributes
  app/assets/images/MaMpf-Logo.svg
  app/assets/images/landing-background.jpg
  app/assets/stylesheets/landing.scss
  app/helpers/application_helper.rb
  app/models/announcement.rb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/layouts/_head.html.erb
  app/views/layouts/devise.html.erb
  app/views/shared/_footer.html.erb
  config/locales/de.yml
  config/locales/devise.de.yml
  config/locales/devise.en.yml
  config/locales/en.yml
  config/routes.rb
  docker/development/docker-compose.yml
Labels: enhancement

#449 fix missing media in user edit view
  app/views/users/_data.html.erb
Labels: bug

#443 Update Rails and gems
  Gemfile
  Gemfile.lock
  README.md
  db/migrate/20230407093205_change_deletion_date_default_in_assignemnts.rb
  db/schema.rb
  docker/development/Dockerfile
  docker/development/docker-compose.yml
  docker/production/Dockerfile
  docker/run_cypress_tests/Dockerfile
  docker/run_cypress_tests/docker-compose.local.yml
  docker/run_cypress_tests/docker-compose.yml
  docker/run_tests/Dockerfile
  docker/run_tests/docker-compose.yml
Labels: dependencies

#455 Improve landing page (small changes)
  app/assets/stylesheets/landing.scss
  app/views/devise/sessions/new.html.erb
  app/views/layouts/devise.html.erb
  config/locales/de.yml
  config/locales/devise.de.yml
  config/locales/en.yml
Labels: enhancement

#446 Redesign left navbar
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/sidebar.scss
  app/helpers/application_helper.rb
  app/views/layouts/application.html.erb
  app/views/shared/_sidebar.html.erb
  config/locales/de.yml
  config/locales/en.yml
Labels: enhancement

#451 Redesign top navbar
  app/assets/stylesheets/navbar.scss
  app/assets/stylesheets/sidebar.scss
  app/helpers/application_helper.rb
  app/views/shared/_navbar.html.erb
  config/locales/de.yml
  config/locales/en.yml
Labels: enhancement

#457 Release of version 1.4.4
  .gitattributes
  Gemfile
  Gemfile.lock
  INSTALL.md
  README.md
  app/assets/images/MaMpf-Logo.svg
  app/assets/images/landing-background.jpg
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/landing.scss
  app/assets/stylesheets/navbar.scss
  app/assets/stylesheets/sidebar.scss
  app/helpers/application_helper.rb
  app/models/announcement.rb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/layouts/_head.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/devise.html.erb
  app/views/shared/_footer.html.erb
  app/views/shared/_navbar.html.erb
  app/views/shared/_sidebar.html.erb
  config/locales/de.yml
  config/locales/devise.de.yml
  config/locales/devise.en.yml
  config/locales/en.yml
  config/routes.rb
  db/migrate/20230407093205_change_deletion_date_default_in_assignemnts.rb
  db/schema.rb
  docker/development/Dockerfile
  docker/development/docker-compose.yml
  docker/production/Dockerfile
  docker/run_cypress_tests/Dockerfile
  docker/run_cypress_tests/docker-compose.local.yml
  docker/run_cypress_tests/docker-compose.yml
  docker/run_tests/Dockerfile
  docker/run_tests/docker-compose.yml
Labels: release

#458 Production release of v1.4.4
  .gitattributes
  Gemfile
  Gemfile.lock
  INSTALL.md
  README.md
  app/assets/images/MaMpf-Logo.svg
  app/assets/images/landing-background.jpg
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/landing.scss
  app/assets/stylesheets/navbar.scss
  app/assets/stylesheets/sidebar.scss
  app/helpers/application_helper.rb
  app/models/announcement.rb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/layouts/_head.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/devise.html.erb
  app/views/shared/_footer.html.erb
  app/views/shared/_navbar.html.erb
  app/views/shared/_sidebar.html.erb
  config/locales/de.yml
  config/locales/devise.de.yml
  config/locales/devise.en.yml
  config/locales/en.yml
  config/routes.rb
  db/migrate/20230407093205_change_deletion_date_default_in_assignemnts.rb
  db/schema.rb
  docker/development/Dockerfile
  docker/development/docker-compose.yml
  docker/production/Dockerfile
  docker/run_cypress_tests/Dockerfile
  docker/run_cypress_tests/docker-compose.local.yml
  docker/run_cypress_tests/docker-compose.yml
  docker/run_tests/Dockerfile
  docker/run_tests/docker-compose.yml
Labels: release

#459 Hotfix for searchbar
  app/views/shared/_sidebar.html.erb
Labels: bug

#470 Avoid confusion with "Request data" button
  app/views/profile/_data.html.erb
  app/views/profile/edit.html.erb
  config/locales/de.yml
  config/locales/en.yml
Labels: enhancement

#465 Use a modal to show sponsors
  app/assets/javascripts/footer_modal.js
  app/views/main/_sponsors.html.erb
  app/views/main/sponsors.html.erb
  app/views/shared/_footer.html.erb
  config/locales/de.yml
  config/locales/en.yml
  config/routes.rb
Labels: enhancement

#471 Always show module sidebar link
  app/views/shared/_sidebar.html.erb
Labels: bug

#480 Add display text for external medium links
  app/assets/stylesheets/media.scss
  app/controllers/media_controller.rb
  app/helpers/media_helper.rb
  app/views/media/_external_link.html.erb
  app/views/media/_external_link_card.html.erb
  app/views/media/medium/_buttons.html.erb
  config/locales/de.yml
  config/locales/en.yml
  db/migrate/20230427124337_add_external_reference_link_description_to_medium.rb
  db/schema.rb
Labels: enhancement

#482 [Security fix] Add authorization to generic user list API
  app/controllers/users_controller.rb
Labels: bug

#478 Deploy from main branch (not production branch)
  docker/production/docker-compose.production.yml
Labels: CI/CD

#485 Update gems
  Gemfile.lock
  app/controllers/users_controller.rb
  app/views/users/_basics.html.erb
  config/routes.rb
Labels: dependencies
