Repository MaMpf-HD/mampf, pull requests merged in 2023-05, with the labels that each got.

#475 Fix decoloring of comments icon
  app/views/commontator/comments/create.js.erb
  app/views/readers/update.coffee
  app/views/readers/update_all.coffee
Labels: bug

#481 Continuous release v1.5.0
  .github/workflows/codecov.yml
  .github/workflows/linter.yml
  .github/workflows/test-integration.yml
  .github/workflows/tests.yml
  app/assets/stylesheets/media.scss
  app/controllers/media_controller.rb
  app/helpers/media_helper.rb
  app/views/commontator/comments/create.js.erb
  app/views/media/_external_link.html.erb
  app/views/media/_external_link_card.html.erb
  app/views/media/medium/_buttons.html.erb
  app/views/readers/update.coffee
  app/views/readers/update_all.coffee
  config/locales/de.yml
  config/locales/en.yml
  db/migrate/20230427124337_add_external_reference_link_description_to_medium.rb
  db/schema.rb
  docker/production/docker-compose.production.yml
  docker/run_cypress_tests/Dockerfile
  docker/run_cypress_tests/docker-compose.yml
  docker/run_tests/Dockerfile
  docker/run_tests/docker-compose.yml
  docker/run_tests/run_tests.sh
  spec/cypress/e2e/simple_spec.cy.js
  spec/cypress/e2e/testing_spec.cy.js
  spec/cypress/e2e/tutorials_spec.cy.js
  spec/cypress/e2e/watchlists_spec.cy.js
Labels: release

#491 Hotfix: correct check for external reference description
  app/helpers/media_helper.rb
Labels: bug

#494 Update rubocop version
  .rubocop.yml
  Gemfile
  Gemfile.lock
Labels: dependencies

#499 Fix color for comment previews
  app/assets/stylesheets/navbar.scss
Labels: bug

#500 Fix ghost links in nested tabs
  app/assets/stylesheets/media.scss
  app/views/lectures/edit/_media.html.erb
  app/views/media/_table_column.html.erb
Labels: bug

#452 Restrict editor access
  app/abilities/lecture_ability.rb
  app/abilities/quiz_certificate_ability.rb
  app/abilities/tutorial_ability.rb
  app/abilities/user_ability.rb
  app/assets/javascripts/lectures.coffee
  app/controllers/lectures_controller.rb
  app/controllers/media_controller.rb
  app/models/lecture.rb
  app/models/medium.rb
  app/models/user.rb
  app/views/lectures/edit/_form.html.erb
  app/views/lectures/edit/_people.html.erb
  app/views/lectures/edit/_tutorials.html.erb
  app/views/media/_basics.html.erb
  config/locales/de.yml
  config/locales/en.yml
Labels: enhancement

#502 Fix flickering for quiz previews
  app/views/media/fill_quizzable_preview.coffee
Labels: bug
