Repository MaMpf-HD/mampf, pull requests merged in 2023-07, with the labels that each got.

#523 Fix masonry grid not properly rendered on page load
  app/javascript/packs/application.js
  app/views/layouts/_head.html.erb
  app/views/lectures/edit/_content.html.erb
  app/views/lectures/edit/_seminar_content.html.erb
  app/views/lectures/show/_content.html.erb
  app/views/lectures/show/_structures.html.erb
Labels: bug

#515 Disable coloring of comments icon for comments created by user itself
  app/controllers/commontator/comments_controller.rb
Labels: enhancement

#526 Replace datetimepicker
  app/assets/javascripts/datetimepicker.js
  app/assets/javascripts/media.coffee
  app/javascript/packs/application.js
  app/javascript/packs/application.sass
  app/views/assignments/_form.html.erb
  app/views/assignments/_row.html.erb
  app/views/assignments/create.coffee
  app/views/assignments/edit.coffee
  app/views/assignments/new.js.erb
  app/views/assignments/update.coffee
  app/views/layouts/_head.html.erb
  app/views/lectures/edit/_assignments.html.erb
  app/views/media/_publish_modal.html.erb
  config/locales/de.yml
  config/locales/en.yml
  package.json
  yarn.lock
Labels: enhancement, dependencies

#531 Fix application bundle not being served by webpacker in dev-setup
  config/webpacker.yml
Labels: bug
