Repository MaMpf-HD/mampf, pull requests merged in 2024-08, with the labels that each got.

#669 Add endpoint to skip validation in Cypress tests
  app/controllers/cypress/factories_controller.rb
  docker/test/docker-compose.yml
  spec/cypress/support/factorybot.js
Labels: tests

#672 Update Gemfile dependencies
  Gemfile.lock
Labels: dependencies

#673 Update yarn dependencies
  yarn.lock
Labels: dependencies

#674 Add UI feedback for closing/opening discussions
  app/controllers/lectures_controller.rb
  app/views/lectures/edit/_comments.html.erb
Labels: enhancement

#668 Add annotations overview page & improve Cypress commands
  .config/.cypress.js
  .config/eslint.mjs
  .vscode/settings.json
  app/abilities/annotation_ability.rb
  app/assets/javascripts/annotations_overview.js
  app/assets/javascripts/application.js
  app/assets/javascripts/thyme/annotations/annotation_manager.js
  app/assets/javascripts/thyme/annotations/url_annotation_opener.js
  app/assets/javascripts/thyme/attributes.js
  app/assets/javascripts/thyme/thyme_feedback.js
  app/assets/javascripts/thyme/thyme_player.js
  app/assets/stylesheets/annotations.scss
  app/assets/stylesheets/annotations_overview.scss
  app/controllers/annotations_controller.rb
  app/controllers/cypress/cypress_controller.rb
  app/controllers/cypress/i18n_controller.rb
  app/controllers/media_controller.rb
  app/helpers/annotations_helper.rb
  app/helpers/media_helper.rb
  app/models/user.rb
  app/views/annotations/_annotation_area.html.erb
  app/views/annotations/_index_accordion.html.erb
  app/views/annotations/index.html.erb
  app/views/commontator/comments/_body.html.erb
  app/views/media/feedback.html.erb
  app/views/media/play.html.erb
  app/views/shared/_navbar.html.erb
  config/environments/test.rb
  config/initializers/shrine.rb
  config/locales/de.yml
  config/locales/en.yml
  config/routes.rb
  spec/cypress/e2e/annotations_overview_spec.cy.js
  spec/cypress/support/commands.js
  spec/cypress/support/utility.js
  spec/factories/annotations.rb
  spec/factories/lectures.rb
  spec/factories/media.rb
Labels: enhancement

#676 Tests: Fix database cleaner separation
  spec/support/database_cleaner.rb
Labels: tests

#647 Delete users that haven't logged in for too long
  app/mailers/mathi_mailer.rb
  app/mailers/user_cleaner_mailer.rb
  app/models/user_cleaner.rb
  app/views/layouts/warning_mail_layout.html.erb
  app/views/mathi_mailer/ghost_email.html.erb
  app/views/user_cleaner_mailer/deletion_email.html.erb
  app/views/user_cleaner_mailer/pending_deletion_email.html.erb
  app/workers/user_cleaner.rb
  app/workers/user_cleaner_job.rb
  config/environments/production.rb
  config/initializers/after_sign_in.rb
  config/locales/de.yml
  config/locales/en.yml
  config/schedule.yml
  db/migrate/20240530200000_add_deletion_date_to_user.rb
  db/migrate/20240605200000_remove_ghost_hash_from_user.rb
  db/schema.rb
  docker/development/docker-compose.yml
  docker/production/docker-compose.production.yml
  docker/production/docker.env
  docker/test/docker-compose.yml
  spec/factories/user_cleaners.rb
  spec/models/teachable_parser_spec.rb
  spec/models/user_cleaner_spec.rb
  spec/rails_helper.rb
Labels: enhancement

#678 Fix failing UserCleanerJob
  app/workers/user_cleaner_job.rb
Labels: bug

#683 Fix lecture edit page if active term is not set
  app/models/lecture.rb
  app/views/lectures/edit/_form.html.erb
  spec/cypress/e2e/lectures_spec.cy.js
  spec/factories/terms.rb
  spec/models/lecture_spec.rb
Labels: bug

#680 Clean up Gemfile & pin all gems
  .gitignore
  Gemfile
  Gemfile.lock
  config/database.yml
  docker/development/Dockerfile
  docker/test/Dockerfile
Labels: dependencies
