Repository MaMpf-HD/mampf, pull requests merged in 2024-11, with the labels that each got.

#705 Add Ruby Test explorer to recommended VSCode extensions
  .vscode/extensions.json
Labels: ide

#715 Hotfix: Set retry option to false for UserCleanerJob
  app/workers/user_cleaner_job.rb
Labels: hotfix

#711 Init dependencies (deps) Just commands
  .config/commands/deps.justfile
  .justfile
Labels: dependencies

#716 Deal with registration edge cases in UserCleaner (cherry-pick #693)
  app/models/user.rb
  app/models/user_cleaner.rb
  spec/factories/users.rb
  spec/models/user_cleaner_spec.rb
Labels: hotfix
