Repository MaMpf-HD/mampf, pull requests merged in 2024-05, with the labels that each got.

#633 Upgrade Gemfile and yarn dependencies
  Gemfile.lock
  yarn.lock
Labels: dependencies

#636 Upgrade Node.js dev dependencies & fix ESLint config
  .config/eslint.mjs
  package.json
  yarn.lock
Labels: dependencies

#581 Add unit tests back to pipeline & improve VSCode integration
  .config/.codecov.yml
  .dockerignore
  .github/workflows/docker-compose-cache.json
  .github/workflows/tests.yml
  .vscode/settings.json
  Gemfile
  Gemfile.lock
  config/webpack/test.js
  docker/test/Dockerfile
  docker/test/Dockerfile_cypress
  docker/test/docker-compose.local.yml
  docker/test/docker-compose.yml
  docker/test/run_tests.sh
  spec/factories/users.rb
  spec/models/announcement_spec.rb
  spec/models/answer_spec.rb
  spec/models/chapter_spec.rb
  spec/models/consumption_spec.rb
  spec/models/course_spec.rb
  spec/models/interaction_spec.rb
  spec/models/lecture_spec.rb
  spec/models/medium_publisher_spec.rb
  spec/models/medium_spec.rb
  spec/models/notion_spec.rb
  spec/models/probe_spec.rb
  spec/models/question_sampler_spec.rb
  spec/models/question_spec.rb
  spec/models/quiz_certificate_spec.rb
  spec/models/quiz_graph_spec.rb
  spec/models/quiz_spec.rb
  spec/models/referral_spec.rb
  spec/models/submission_cleaner_spec.rb
  spec/models/talk_spec.rb
  spec/models/talk_tag_join_spec.rb
  spec/models/teachable_parser_spec.rb
  spec/models/term_spec.rb
  spec/models/user_cleaner_spec.rb
  spec/models/user_spec.rb
  spec/rails_helper.rb
  spec/requests/media_spec.rb
  spec/rspec_inside_docker.py
  spec/support/database_cleaner.rb
  spec/support/request_parse_helper.rb
Labels: CI/CD, tests, ide

#643 Pin `thredded` to recent Git commit
  Gemfile
  Gemfile.lock
Labels: dependencies

#644 Open interactive area if chapters or references are present in video
  app/assets/javascripts/thyme/chapter_manager.js
  app/assets/javascripts/thyme/metadata_manager.js
  app/assets/javascripts/thyme/thyme_player.js
Labels: enhancement

#640 Fix broken deletion of questions
  app/models/medium.rb
Labels: bug

#628 Redesign lecture edit page for lecturers
  .config/eslint.mjs
  app/assets/javascripts/application.js
  app/assets/javascripts/lectures.coffee
  app/assets/javascripts/lectures.js
  app/assets/javascripts/lectures_admin.js
  app/assets/javascripts/masonry_grid.js
  app/assets/stylesheets/lectures.scss
  app/controllers/announcements_controller.rb
  app/controllers/lectures_controller.rb
  app/javascript/packs/application.js
  app/models/lecture.rb
  app/views/assignments/_form.html.erb
  app/views/lectures/edit/_announcements.html.erb
  app/views/lectures/edit/_assignments.html.erb
  app/views/lectures/edit/_comments.html.erb
  app/views/lectures/edit/_erdbeere.html.erb
  app/views/lectures/edit/_form.html.erb
  app/views/lectures/edit/_forum.html.erb
  app/views/lectures/edit/_header.html.erb
  app/views/lectures/edit/_imported_media.html.erb
  app/views/lectures/edit/_organizational_concept.html.erb
  app/views/lectures/edit/_people.html.erb
  app/views/lectures/edit/_preferences.html.erb
  app/views/lectures/edit/_structures.html.erb
  app/views/lectures/edit/_tags.html.erb
  app/views/lectures/edit/_tutorials.html.erb
  app/views/lectures/edit_structures.coffee
  app/views/lectures/update.coffee
  app/views/tutorials/_form.html.erb
  config/locales/de.yml
  config/locales/en.yml
Labels: enhancement
